/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clickerrpg.ui;

import clickerrpg.MainClass;
import CheongKaMeng.SortedHelperList;
import CheongKaMeng.SortedHelperListInterface;
import clickerrpg.Helper;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Louis Cheong
 */
public class HelperUI extends javax.swing.JFrame {
    private static int page = 1;
    /**
     * Creates new form HelperUI
     */
    public HelperUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPrevPage = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        labelGold = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblDamage = new javax.swing.JLabel();
        btnUpgrade = new javax.swing.JButton();
        btnHire = new javax.swing.JButton();
        lblUpgradeCost = new javax.swing.JLabel();
        lblDamageValue = new javax.swing.JLabel();
        lblUpgradeCostValue = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblHireCost = new javax.swing.JLabel();
        lblHireCostValue = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblName5 = new javax.swing.JLabel();
        lblDamage5 = new javax.swing.JLabel();
        btnUpgrade5 = new javax.swing.JButton();
        btnHire5 = new javax.swing.JButton();
        lblUpgradeCost5 = new javax.swing.JLabel();
        lblDamageValue5 = new javax.swing.JLabel();
        lblUpgradeCostValue5 = new javax.swing.JLabel();
        lblIcon5 = new javax.swing.JLabel();
        lblHireCost5 = new javax.swing.JLabel();
        lblHireCostValue5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblName6 = new javax.swing.JLabel();
        lblDamage6 = new javax.swing.JLabel();
        btnUpgrade6 = new javax.swing.JButton();
        btnHire6 = new javax.swing.JButton();
        lblUpgradeCost6 = new javax.swing.JLabel();
        lblDamageValue6 = new javax.swing.JLabel();
        lblUpgradeCostValue6 = new javax.swing.JLabel();
        lblIcon6 = new javax.swing.JLabel();
        lblHireCost6 = new javax.swing.JLabel();
        lblHireCostValue6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblName7 = new javax.swing.JLabel();
        lblDamage7 = new javax.swing.JLabel();
        btnUpgrade7 = new javax.swing.JButton();
        btnHire7 = new javax.swing.JButton();
        lblUpgradeCost7 = new javax.swing.JLabel();
        lblDamageValue7 = new javax.swing.JLabel();
        lblUpgradeCostValue7 = new javax.swing.JLabel();
        lblIcon7 = new javax.swing.JLabel();
        lblHireCost7 = new javax.swing.JLabel();
        lblHireCostValue7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(705, 550));
        setMinimumSize(new java.awt.Dimension(705, 550));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(705, 550));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnPrevPage.setBackground(new java.awt.Color(51, 51, 51));
        btnPrevPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrevPage.setForeground(new java.awt.Color(153, 153, 153));
        btnPrevPage.setText("Previous Page");
        btnPrevPage.setFocusPainted(false);
        btnPrevPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevPageActionPerformed(evt);
            }
        });

        btnNextPage.setBackground(new java.awt.Color(51, 51, 51));
        btnNextPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNextPage.setForeground(new java.awt.Color(153, 153, 153));
        btnNextPage.setText("Next Page");
        btnNextPage.setFocusPainted(false);
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 153, 153));
        btnBack.setText("Back");
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        labelGold.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelGold.setForeground(new java.awt.Color(255, 215, 0));
        labelGold.setText("999 999 999");
        labelGold.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 215, 0));
        jLabel1.setText("$");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 204, 204));
        lblName.setText("Helper1");

        lblDamage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDamage.setForeground(new java.awt.Color(204, 204, 204));
        lblDamage.setText("Damage:");

        btnUpgrade.setBackground(new java.awt.Color(51, 51, 51));
        btnUpgrade.setForeground(new java.awt.Color(153, 153, 153));
        btnUpgrade.setText("Upgrade");
        btnUpgrade.setFocusPainted(false);
        btnUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgradeActionPerformed(evt);
            }
        });

        btnHire.setBackground(new java.awt.Color(51, 51, 51));
        btnHire.setForeground(new java.awt.Color(153, 153, 153));
        btnHire.setText("Hire");
        btnHire.setFocusPainted(false);
        btnHire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHireActionPerformed(evt);
            }
        });

        lblUpgradeCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUpgradeCost.setForeground(new java.awt.Color(204, 204, 204));
        lblUpgradeCost.setText("Upgrade Cost: $");

        lblDamageValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDamageValue.setForeground(new java.awt.Color(204, 204, 204));
        lblDamageValue.setText("30");

        lblUpgradeCostValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUpgradeCostValue.setForeground(new java.awt.Color(204, 204, 204));
        lblUpgradeCostValue.setText("100");

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/player150x90.png"))); // NOI18N
        lblIcon.setText("icon");

        lblHireCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHireCost.setForeground(new java.awt.Color(204, 204, 204));
        lblHireCost.setText("Hire Cost: $");

        lblHireCostValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHireCostValue.setForeground(new java.awt.Color(204, 204, 204));
        lblHireCostValue.setText("100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnUpgrade))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHireCost)
                                    .addComponent(lblUpgradeCost))
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHireCostValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpgradeCostValue, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnHire))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblDamageValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDamage)
                    .addComponent(lblDamageValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpgradeCost)
                    .addComponent(lblUpgradeCostValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHireCostValue)
                    .addComponent(lblHireCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpgrade)
                    .addComponent(btnHire))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName5.setForeground(new java.awt.Color(204, 204, 204));
        lblName5.setText("Helper1");

        lblDamage5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDamage5.setForeground(new java.awt.Color(204, 204, 204));
        lblDamage5.setText("Damage:");

        btnUpgrade5.setBackground(new java.awt.Color(51, 51, 51));
        btnUpgrade5.setForeground(new java.awt.Color(153, 153, 153));
        btnUpgrade5.setText("Upgrade");
        btnUpgrade5.setFocusPainted(false);
        btnUpgrade5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgrade5ActionPerformed(evt);
            }
        });

        btnHire5.setBackground(new java.awt.Color(51, 51, 51));
        btnHire5.setForeground(new java.awt.Color(153, 153, 153));
        btnHire5.setText("Hire");
        btnHire5.setFocusPainted(false);
        btnHire5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHire5ActionPerformed(evt);
            }
        });

        lblUpgradeCost5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUpgradeCost5.setForeground(new java.awt.Color(204, 204, 204));
        lblUpgradeCost5.setText("Upgrade Cost: $");

        lblDamageValue5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDamageValue5.setForeground(new java.awt.Color(204, 204, 204));
        lblDamageValue5.setText("30");

        lblUpgradeCostValue5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUpgradeCostValue5.setForeground(new java.awt.Color(204, 204, 204));
        lblUpgradeCostValue5.setText("100");

        lblIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/player150x90.png"))); // NOI18N
        lblIcon5.setText("icon");

        lblHireCost5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHireCost5.setForeground(new java.awt.Color(204, 204, 204));
        lblHireCost5.setText("Hire Cost: $");

        lblHireCostValue5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHireCostValue5.setForeground(new java.awt.Color(204, 204, 204));
        lblHireCostValue5.setText("100");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblName5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnUpgrade5))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHireCost5)
                                    .addComponent(lblUpgradeCost5))
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHireCostValue5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpgradeCostValue5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnHire5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(lblDamage5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblDamageValue5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblIcon5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDamage5)
                    .addComponent(lblDamageValue5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpgradeCost5)
                    .addComponent(lblUpgradeCostValue5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHireCostValue5)
                    .addComponent(lblHireCost5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpgrade5)
                    .addComponent(btnHire5))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName6.setForeground(new java.awt.Color(204, 204, 204));
        lblName6.setText("Helper1");

        lblDamage6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDamage6.setForeground(new java.awt.Color(204, 204, 204));
        lblDamage6.setText("Damage:");

        btnUpgrade6.setBackground(new java.awt.Color(51, 51, 51));
        btnUpgrade6.setForeground(new java.awt.Color(153, 153, 153));
        btnUpgrade6.setText("Upgrade");
        btnUpgrade6.setFocusPainted(false);
        btnUpgrade6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgrade6ActionPerformed(evt);
            }
        });

        btnHire6.setBackground(new java.awt.Color(51, 51, 51));
        btnHire6.setForeground(new java.awt.Color(153, 153, 153));
        btnHire6.setText("Hire");
        btnHire6.setFocusPainted(false);
        btnHire6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHire6ActionPerformed(evt);
            }
        });

        lblUpgradeCost6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUpgradeCost6.setForeground(new java.awt.Color(204, 204, 204));
        lblUpgradeCost6.setText("Upgrade Cost: $");

        lblDamageValue6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDamageValue6.setForeground(new java.awt.Color(204, 204, 204));
        lblDamageValue6.setText("30");

        lblUpgradeCostValue6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUpgradeCostValue6.setForeground(new java.awt.Color(204, 204, 204));
        lblUpgradeCostValue6.setText("100");

        lblIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/player150x90.png"))); // NOI18N
        lblIcon6.setText("icon");

        lblHireCost6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHireCost6.setForeground(new java.awt.Color(204, 204, 204));
        lblHireCost6.setText("Hire Cost: $");

        lblHireCostValue6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHireCostValue6.setForeground(new java.awt.Color(204, 204, 204));
        lblHireCostValue6.setText("100");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblName6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnUpgrade6))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHireCost6)
                                    .addComponent(lblUpgradeCost6))
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHireCostValue6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpgradeCostValue6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnHire6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(lblDamage6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblDamageValue6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblIcon6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDamage6)
                    .addComponent(lblDamageValue6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpgradeCost6)
                    .addComponent(lblUpgradeCostValue6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHireCostValue6)
                    .addComponent(lblHireCost6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpgrade6)
                    .addComponent(btnHire6))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName7.setForeground(new java.awt.Color(204, 204, 204));
        lblName7.setText("Helper1");

        lblDamage7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDamage7.setForeground(new java.awt.Color(204, 204, 204));
        lblDamage7.setText("Damage:");

        btnUpgrade7.setBackground(new java.awt.Color(51, 51, 51));
        btnUpgrade7.setForeground(new java.awt.Color(153, 153, 153));
        btnUpgrade7.setText("Upgrade");
        btnUpgrade7.setFocusPainted(false);
        btnUpgrade7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgrade7ActionPerformed(evt);
            }
        });

        btnHire7.setBackground(new java.awt.Color(51, 51, 51));
        btnHire7.setForeground(new java.awt.Color(153, 153, 153));
        btnHire7.setText("Hire");
        btnHire7.setFocusPainted(false);
        btnHire7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHire7ActionPerformed(evt);
            }
        });

        lblUpgradeCost7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUpgradeCost7.setForeground(new java.awt.Color(204, 204, 204));
        lblUpgradeCost7.setText("Upgrade Cost: $");

        lblDamageValue7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDamageValue7.setForeground(new java.awt.Color(204, 204, 204));
        lblDamageValue7.setText("30");

        lblUpgradeCostValue7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUpgradeCostValue7.setForeground(new java.awt.Color(204, 204, 204));
        lblUpgradeCostValue7.setText("100");

        lblIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/player150x90.png"))); // NOI18N
        lblIcon7.setText("icon");

        lblHireCost7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHireCost7.setForeground(new java.awt.Color(204, 204, 204));
        lblHireCost7.setText("Hire Cost: $");

        lblHireCostValue7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHireCostValue7.setForeground(new java.awt.Color(204, 204, 204));
        lblHireCostValue7.setText("100");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lblName7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnUpgrade7))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHireCost7)
                                    .addComponent(lblUpgradeCost7))
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHireCostValue7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpgradeCostValue7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnHire7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(lblDamage7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblDamageValue7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblIcon7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDamage7)
                    .addComponent(lblDamageValue7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpgradeCost7)
                    .addComponent(lblUpgradeCostValue7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHireCostValue7)
                    .addComponent(lblHireCost7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpgrade7)
                    .addComponent(btnHire7))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrevPage)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(labelGold)
                    .addContainerGap(440, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevPage)
                    .addComponent(btnBack)
                    .addComponent(btnNextPage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(labelGold))
                    .addContainerGap(486, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpgradeActionPerformed

    private void btnHireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHireActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPrevPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevPageActionPerformed
        // TODO add your handling code here:
        if (page == 2){
            page--;
            updateUI();
        }
    }//GEN-LAST:event_btnPrevPageActionPerformed

    private void btnUpgrade5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgrade5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpgrade5ActionPerformed

    private void btnHire5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHire5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHire5ActionPerformed

    private void btnUpgrade6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgrade6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpgrade6ActionPerformed

    private void btnHire6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHire6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHire6ActionPerformed

    private void btnUpgrade7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgrade7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpgrade7ActionPerformed

    private void btnHire7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHire7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHire7ActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        // TODO add your handling code here:
        if (page == 1){
            page++;
            updateUI();
        }
    }//GEN-LAST:event_btnNextPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelperUI().setVisible(true);
            }
        });
    }

    public void startUp(){
        updateUI();
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private void updateUI() {
        updatePanel1Control(MainClass.helperList.get(page * 4 - 4));
        updatePanel2Control(MainClass.helperList.get(page* 4 - 3));
        updatePanel3Control(MainClass.helperList.get(page* 4 - 2));
        updatePanel4Control(MainClass.helperList.get(page * 4 - 1));
    }
    private void updatePanel1Control(Helper helper) {
        lblName.setText(helper.getName());
        lblDamageValue.setText(String.valueOf(helper.getDamage()));
        lblHireCostValue.setText(String.valueOf(helper.getHireCost()));
        lblUpgradeCostValue.setText(String.valueOf(helper.getLevelUpCost()));
    }
    
    private void updatePanel2Control(Helper helper) {
        lblName5.setText(helper.getName());
        lblDamageValue5.setText(String.valueOf(helper.getDamage()));
        lblHireCostValue5.setText(String.valueOf(helper.getHireCost()));
        lblUpgradeCostValue5.setText(String.valueOf(helper.getLevelUpCost()));
    }
    
    private void updatePanel3Control(Helper helper) {
        lblName6.setText(helper.getName());
        lblDamageValue6.setText(String.valueOf(helper.getDamage()));
        lblHireCostValue6.setText(String.valueOf(helper.getHireCost()));
        lblUpgradeCostValue6.setText(String.valueOf(helper.getLevelUpCost()));
    }
    
    private void updatePanel4Control(Helper helper) {
        lblName7.setText(helper.getName());
        lblDamageValue7.setText(String.valueOf(helper.getDamage()));
        lblHireCostValue7.setText(String.valueOf(helper.getHireCost()));
        lblUpgradeCostValue7.setText(String.valueOf(helper.getLevelUpCost()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHire;
    private javax.swing.JButton btnHire5;
    private javax.swing.JButton btnHire6;
    private javax.swing.JButton btnHire7;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnPrevPage;
    private javax.swing.JButton btnUpgrade;
    private javax.swing.JButton btnUpgrade5;
    private javax.swing.JButton btnUpgrade6;
    private javax.swing.JButton btnUpgrade7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelGold;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JLabel lblDamage5;
    private javax.swing.JLabel lblDamage6;
    private javax.swing.JLabel lblDamage7;
    private javax.swing.JLabel lblDamageValue;
    private javax.swing.JLabel lblDamageValue5;
    private javax.swing.JLabel lblDamageValue6;
    private javax.swing.JLabel lblDamageValue7;
    private javax.swing.JLabel lblHireCost;
    private javax.swing.JLabel lblHireCost5;
    private javax.swing.JLabel lblHireCost6;
    private javax.swing.JLabel lblHireCost7;
    private javax.swing.JLabel lblHireCostValue;
    private javax.swing.JLabel lblHireCostValue5;
    private javax.swing.JLabel lblHireCostValue6;
    private javax.swing.JLabel lblHireCostValue7;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon5;
    private javax.swing.JLabel lblIcon6;
    private javax.swing.JLabel lblIcon7;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblUpgradeCost;
    private javax.swing.JLabel lblUpgradeCost5;
    private javax.swing.JLabel lblUpgradeCost6;
    private javax.swing.JLabel lblUpgradeCost7;
    private javax.swing.JLabel lblUpgradeCostValue;
    private javax.swing.JLabel lblUpgradeCostValue5;
    private javax.swing.JLabel lblUpgradeCostValue6;
    private javax.swing.JLabel lblUpgradeCostValue7;
    // End of variables declaration//GEN-END:variables
}
