/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clickerrpg.ui;

import clickerrpg.MainClass;
import ADT.CheongKaMeng.SortedHelperList;
import ADT.CheongKaMeng.SortedHelperListInterface;
import clickerrpg.Helper;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Louis Cheong
 */
public class HelperUI extends javax.swing.JFrame {

    private static int page = 1;
    private final String imageFolderPath = "src/clickerrpg/img/";

    /**
     * Creates new form HelperUI
     */
    public HelperUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPrevPage = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        labelGold = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        btnUpgrade = new javax.swing.JButton();
        btnHire = new javax.swing.JButton();
        lblDamage = new javax.swing.JLabel();
        lblLevelValue = new javax.swing.JLabel();
        lblDamageValue = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblCostValue = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        lblLevel1 = new javax.swing.JLabel();
        btnUpgrade1 = new javax.swing.JButton();
        btnHire1 = new javax.swing.JButton();
        lblDamage1 = new javax.swing.JLabel();
        lblLevelValue1 = new javax.swing.JLabel();
        lblDamageValue1 = new javax.swing.JLabel();
        lblIcon1 = new javax.swing.JLabel();
        lblCost1 = new javax.swing.JLabel();
        lblCostValue1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblName2 = new javax.swing.JLabel();
        lblLevel2 = new javax.swing.JLabel();
        btnUpgrade2 = new javax.swing.JButton();
        btnHire2 = new javax.swing.JButton();
        lblDamage2 = new javax.swing.JLabel();
        lblLevelValue2 = new javax.swing.JLabel();
        lblDamageValue2 = new javax.swing.JLabel();
        lblIcon2 = new javax.swing.JLabel();
        lblCost2 = new javax.swing.JLabel();
        lblCostValue2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblName3 = new javax.swing.JLabel();
        lblLevel3 = new javax.swing.JLabel();
        btnUpgrade3 = new javax.swing.JButton();
        btnHire3 = new javax.swing.JButton();
        lblDamage3 = new javax.swing.JLabel();
        lblLevelValue3 = new javax.swing.JLabel();
        lblDamageValue3 = new javax.swing.JLabel();
        lblIcon3 = new javax.swing.JLabel();
        lblCost3 = new javax.swing.JLabel();
        lblCostValue3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(705, 550));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(705, 550));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPrevPage.setBackground(new java.awt.Color(51, 51, 51));
        btnPrevPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrevPage.setForeground(new java.awt.Color(153, 153, 153));
        btnPrevPage.setText("Previous Page");
        btnPrevPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrevPage.setFocusPainted(false);
        btnPrevPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnPrevPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevPageActionPerformed(evt);
            }
        });

        btnNextPage.setBackground(new java.awt.Color(51, 51, 51));
        btnNextPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNextPage.setForeground(new java.awt.Color(153, 153, 153));
        btnNextPage.setText("Next Page");
        btnNextPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNextPage.setFocusPainted(false);
        btnNextPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 153, 153));
        btnBack.setText("Back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        labelGold.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelGold.setForeground(new java.awt.Color(255, 215, 0));
        labelGold.setText("999 999 999");
        labelGold.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 215, 0));
        jLabel1.setText("$");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 204, 204));
        lblName.setText("Helper1");

        lblLevel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(204, 204, 204));
        lblLevel.setText("Level:");

        btnUpgrade.setBackground(new java.awt.Color(51, 51, 51));
        btnUpgrade.setForeground(new java.awt.Color(153, 153, 153));
        btnUpgrade.setText("Upgrade");
        btnUpgrade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpgrade.setEnabled(false);
        btnUpgrade.setFocusPainted(false);
        btnUpgrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgradeActionPerformed(evt);
            }
        });

        btnHire.setBackground(new java.awt.Color(51, 51, 51));
        btnHire.setForeground(new java.awt.Color(153, 153, 153));
        btnHire.setText("Hire");
        btnHire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHire.setFocusPainted(false);
        btnHire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnHire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHireActionPerformed(evt);
            }
        });

        lblDamage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDamage.setForeground(new java.awt.Color(204, 204, 204));
        lblDamage.setText("Damage:");

        lblLevelValue.setBackground(new java.awt.Color(0, 204, 204));
        lblLevelValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLevelValue.setForeground(new java.awt.Color(204, 204, 204));
        lblLevelValue.setText("30");

        lblDamageValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDamageValue.setForeground(new java.awt.Color(204, 204, 204));
        lblDamageValue.setText("100");

        lblIcon.setText("icon");

        lblCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCost.setForeground(new java.awt.Color(204, 204, 204));
        lblCost.setText("Hire Cost: $");

        lblCostValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCostValue.setForeground(new java.awt.Color(204, 204, 204));
        lblCostValue.setText("100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCostValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDamageValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLevelValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(btnUpgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHire, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblIcon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLevel)
                            .addComponent(lblLevelValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDamage)
                            .addComponent(lblDamageValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostValue)
                            .addComponent(lblCost))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHire)
                            .addComponent(btnUpgrade))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName1.setForeground(new java.awt.Color(204, 204, 204));
        lblName1.setText("Helper1");

        lblLevel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLevel1.setForeground(new java.awt.Color(204, 204, 204));
        lblLevel1.setText("Level:");

        btnUpgrade1.setBackground(new java.awt.Color(51, 51, 51));
        btnUpgrade1.setForeground(new java.awt.Color(153, 153, 153));
        btnUpgrade1.setText("Upgrade");
        btnUpgrade1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpgrade1.setEnabled(false);
        btnUpgrade1.setFocusPainted(false);
        btnUpgrade1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnUpgrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgrade1ActionPerformed(evt);
            }
        });

        btnHire1.setBackground(new java.awt.Color(51, 51, 51));
        btnHire1.setForeground(new java.awt.Color(153, 153, 153));
        btnHire1.setText("Hire");
        btnHire1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHire1.setFocusPainted(false);
        btnHire1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnHire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHire1ActionPerformed(evt);
            }
        });

        lblDamage1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDamage1.setForeground(new java.awt.Color(204, 204, 204));
        lblDamage1.setText("Damage:");

        lblLevelValue1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLevelValue1.setForeground(new java.awt.Color(204, 204, 204));
        lblLevelValue1.setText("30");

        lblDamageValue1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDamageValue1.setForeground(new java.awt.Color(204, 204, 204));
        lblDamageValue1.setText("100");

        lblIcon1.setText("icon");

        lblCost1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCost1.setForeground(new java.awt.Color(204, 204, 204));
        lblCost1.setText("Hire Cost: $");

        lblCostValue1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCostValue1.setForeground(new java.awt.Color(204, 204, 204));
        lblCostValue1.setText("100");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCost1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDamage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCostValue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDamageValue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLevelValue1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpgrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHire1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblIcon1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLevel1)
                            .addComponent(lblLevelValue1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDamage1)
                            .addComponent(lblDamageValue1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostValue1)
                            .addComponent(lblCost1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHire1)
                            .addComponent(btnUpgrade1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName2.setForeground(new java.awt.Color(204, 204, 204));
        lblName2.setText("Helper1");

        lblLevel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLevel2.setForeground(new java.awt.Color(204, 204, 204));
        lblLevel2.setText("Level:");

        btnUpgrade2.setBackground(new java.awt.Color(51, 51, 51));
        btnUpgrade2.setForeground(new java.awt.Color(153, 153, 153));
        btnUpgrade2.setText("Upgrade");
        btnUpgrade2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpgrade2.setEnabled(false);
        btnUpgrade2.setFocusPainted(false);
        btnUpgrade2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnUpgrade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgrade2ActionPerformed(evt);
            }
        });

        btnHire2.setBackground(new java.awt.Color(51, 51, 51));
        btnHire2.setForeground(new java.awt.Color(153, 153, 153));
        btnHire2.setText("Hire");
        btnHire2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHire2.setFocusPainted(false);
        btnHire2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnHire2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHire2ActionPerformed(evt);
            }
        });

        lblDamage2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDamage2.setForeground(new java.awt.Color(204, 204, 204));
        lblDamage2.setText("Damage:");

        lblLevelValue2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLevelValue2.setForeground(new java.awt.Color(204, 204, 204));
        lblLevelValue2.setText("30");

        lblDamageValue2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDamageValue2.setForeground(new java.awt.Color(204, 204, 204));
        lblDamageValue2.setText("100");

        lblIcon2.setText("icon");

        lblCost2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCost2.setForeground(new java.awt.Color(204, 204, 204));
        lblCost2.setText("Hire Cost: $");

        lblCostValue2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCostValue2.setForeground(new java.awt.Color(204, 204, 204));
        lblCostValue2.setText("100");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCost2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDamage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCostValue2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDamageValue2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLevelValue2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpgrade2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHire2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblIcon2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLevel2)
                            .addComponent(lblLevelValue2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDamage2)
                            .addComponent(lblDamageValue2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostValue2)
                            .addComponent(lblCost2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHire2)
                            .addComponent(btnUpgrade2))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName3.setForeground(new java.awt.Color(204, 204, 204));
        lblName3.setText("Helper1");

        lblLevel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLevel3.setForeground(new java.awt.Color(204, 204, 204));
        lblLevel3.setText("Level:");

        btnUpgrade3.setBackground(new java.awt.Color(51, 51, 51));
        btnUpgrade3.setForeground(new java.awt.Color(153, 153, 153));
        btnUpgrade3.setText("Upgrade");
        btnUpgrade3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpgrade3.setEnabled(false);
        btnUpgrade3.setFocusPainted(false);
        btnUpgrade3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnUpgrade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgrade3ActionPerformed(evt);
            }
        });

        btnHire3.setBackground(new java.awt.Color(51, 51, 51));
        btnHire3.setForeground(new java.awt.Color(153, 153, 153));
        btnHire3.setText("Hire");
        btnHire3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHire3.setFocusPainted(false);
        btnHire3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextPageMouseExited(evt);
            }
        });
        btnHire3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHire3ActionPerformed(evt);
            }
        });

        lblDamage3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDamage3.setForeground(new java.awt.Color(204, 204, 204));
        lblDamage3.setText("Damage:");

        lblLevelValue3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLevelValue3.setForeground(new java.awt.Color(204, 204, 204));
        lblLevelValue3.setText("30");

        lblDamageValue3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDamageValue3.setForeground(new java.awt.Color(204, 204, 204));
        lblDamageValue3.setText("100");

        lblIcon3.setText("icon");

        lblCost3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCost3.setForeground(new java.awt.Color(204, 204, 204));
        lblCost3.setText("Hire Cost: $");

        lblCostValue3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCostValue3.setForeground(new java.awt.Color(204, 204, 204));
        lblCostValue3.setText("100");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCost3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDamage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblLevel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCostValue3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDamageValue3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLevelValue3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnUpgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHire3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblIcon3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLevel3)
                            .addComponent(lblLevelValue3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDamage3)
                            .addComponent(lblDamageValue3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostValue3)
                            .addComponent(lblCost3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHire3)
                            .addComponent(btnUpgrade3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnPrevPage)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(labelGold)
                    .addContainerGap(595, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevPage)
                    .addComponent(btnBack)
                    .addComponent(btnNextPage))
                .addGap(46, 46, 46))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(labelGold))
                    .addContainerGap(486, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHire3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHire3ActionPerformed
        // TODO add your handling code here:
        hireBtnEvent(MainClass.helperList.get(page * 4 - 1));
    }//GEN-LAST:event_btnHire3ActionPerformed

    private void btnUpgrade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgrade3ActionPerformed
        // TODO add your handling code here:
        upgradeBtnEvent(MainClass.helperList.get(page * 4 - 1));
    }//GEN-LAST:event_btnUpgrade3ActionPerformed

    private void btnHire2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHire2ActionPerformed
        // TODO add your handling code here:
        hireBtnEvent(MainClass.helperList.get(page * 4 - 2));
    }//GEN-LAST:event_btnHire2ActionPerformed

    private void btnUpgrade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgrade2ActionPerformed
        // TODO add your handling code here:
        upgradeBtnEvent(MainClass.helperList.get(page * 4 - 2));
    }//GEN-LAST:event_btnUpgrade2ActionPerformed

    private void btnHire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHire1ActionPerformed
        // TODO add your handling code here:
        hireBtnEvent(MainClass.helperList.get(page * 4 - 3));
    }//GEN-LAST:event_btnHire1ActionPerformed

    private void btnUpgrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgrade1ActionPerformed
        // TODO add your handling code here:
        upgradeBtnEvent(MainClass.helperList.get(page * 4 - 3));
    }//GEN-LAST:event_btnUpgrade1ActionPerformed

    private void btnHireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHireActionPerformed
        // TODO add your handling code here:
        hireBtnEvent(MainClass.helperList.get(page * 4 - 4));
    }//GEN-LAST:event_btnHireActionPerformed

    private void btnUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgradeActionPerformed
        // TODO add your handling code here:
        upgradeBtnEvent(MainClass.helperList.get(page * 4 - 4));
    }//GEN-LAST:event_btnUpgradeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainClass.startAutoAttackTimers();
        MainClass.gameUI.setEnabled(true);
        MainClass.gameUI.toFront();
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        // TODO add your handling code here:
        if (page == 1) {
            page++;
            updateUI();
        }
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void btnPrevPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevPageActionPerformed
        // TODO add your handling code here:
        if (page == 2) {
            page--;
            updateUI();
        }
    }//GEN-LAST:event_btnPrevPageActionPerformed

    private void btnNextPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextPageMouseEntered
        // TODO add your handling code here:
        if (evt.getComponent().isEnabled()) {
            evt.getComponent().setBackground(new Color(80, 80, 80));
        }

    }//GEN-LAST:event_btnNextPageMouseEntered

    private void btnNextPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextPageMouseExited
        // TODO add your handling code here:
        evt.getComponent().setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_btnNextPageMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelperUI().setVisible(true);
            }
        });
    }

    public void startUp() {
        updateUI();
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private void updateUI() {
        labelGold.setText(String.format("%d", (int) MainClass.player.getGold()));
        updatePanel1Control(MainClass.helperList.get(page * 4 - 4));
        updatePanel2Control(MainClass.helperList.get(page * 4 - 3));
        updatePanel3Control(MainClass.helperList.get(page * 4 - 2));
        updatePanel4Control(MainClass.helperList.get(page * 4 - 1));
        if (page == 1) {
            btnPrevPage.setEnabled(false);
            btnNextPage.setEnabled(true);
        } else {
            btnPrevPage.setEnabled(true);
            btnNextPage.setEnabled(false);
        }

    }

    private void hireBtnEvent(Helper helper) {
        if (helper.isHired() == false) {
            MainClass.player.deductGold((int) helper.getHireCost());
            helper.setHired(true);

        } else if (helper.isAssigned() == false) {
            helper.setAssigned(true);
            MainClass.assignedHelperList.add(helper);

        } else {
            helper.setAssigned(false);
            MainClass.assignedHelperList.remove(helper);
        }
        MainClass.gameUI.updateHelper();
        MainClass.gameUI.updateGameUI();
        updateUI();
    }

    private void upgradeBtnEvent(Helper helper) {
        MainClass.player.deductGold((int) helper.getUpgradeCost());
        helper.upgrade();
        MainClass.gameUI.updateGameUI();
        updateUI();
    }

    private void updatePanel1Control(Helper helper) {
        lblIcon.setIcon(new ImageIcon(imageFolderPath + helper.getImageUrl()));
        lblName.setText(helper.getName());
        lblLevelValue.setText(String.format("%d", helper.getLevel()));
        lblDamageValue.setText(String.format("%d", (int) helper.getDamage()));

        if (helper.isHired()) {
            lblCost.setText("Upgrade Cost: $");
            lblCostValue.setText(String.format("%d", (int) helper.getUpgradeCost()));
            btnUpgrade.setEnabled(true);
            btnHire.setEnabled(true);
            if (helper.isAssigned()) {
                btnHire.setText("Unassign");
                jPanel1.setBackground(new Color(102, 0, 0));
            } else {
                btnHire.setText("Assign");
                jPanel1.setBackground(new Color(102, 102, 102));
                if (MainClass.assignedHelperList.size() == 3) {
                    btnHire.setEnabled(false);
                }
            }
            if (MainClass.player.getGold() < helper.getUpgradeCost()) {
                btnUpgrade.setEnabled(false);
            }
        } else {
            jPanel1.setBackground(new Color(51, 51, 51));
            lblCost.setText("Hire Cost: $");
            lblCostValue.setText(String.format("%d", (int) helper.getHireCost()));
            btnHire.setText("Hire");
            btnUpgrade.setEnabled(false);
            if (MainClass.player.getGold() < helper.getHireCost()) {
                btnHire.setEnabled(false);
            } else {
                btnHire.setEnabled(true);
            }
        }
    }

    private void updatePanel2Control(Helper helper) {
        lblIcon1.setIcon(new ImageIcon(imageFolderPath + helper.getImageUrl()));
        lblName1.setText(helper.getName());
        lblLevelValue1.setText(String.format("%d", helper.getLevel()));
        lblDamageValue1.setText(String.format("%d", (int) helper.getDamage()));

        if (helper.isHired()) {
            lblCost1.setText("Upgrade Cost: $");
            lblCostValue1.setText(String.format("%d", (int) helper.getUpgradeCost()));
            btnUpgrade1.setEnabled(true);
            btnHire1.setEnabled(true);
            if (helper.isAssigned()) {
                btnHire1.setText("Unassign");
                jPanel3.setBackground(new Color(102, 0, 0));
            } else {
                btnHire1.setText("Assign");
                jPanel3.setBackground(new Color(102, 102, 102));
                if (MainClass.assignedHelperList.size() == 3) {
                    btnHire1.setEnabled(false);
                }
            }
            if (MainClass.player.getGold() < helper.getUpgradeCost()) {
                btnUpgrade1.setEnabled(false);
            }
        } else {
            jPanel3.setBackground(new Color(51, 51, 51));
            lblCost1.setText("Hire Cost: $");
            lblCostValue1.setText(String.format("%d", (int) helper.getHireCost()));
            btnHire1.setText("Hire");
            btnUpgrade1.setEnabled(false);
            if (MainClass.player.getGold() < helper.getHireCost()) {
                btnHire1.setEnabled(false);
            } else {
                btnHire1.setEnabled(true);
            }
        }
    }

    private void updatePanel3Control(Helper helper) {
        lblIcon2.setIcon(new ImageIcon(imageFolderPath + helper.getImageUrl()));
        lblName2.setText(helper.getName());
        lblLevelValue2.setText(String.format("%d", helper.getLevel()));
        lblDamageValue2.setText(String.format("%d", (int) helper.getDamage()));

        if (helper.isHired()) {
            lblCost2.setText("Upgrade Cost: $");
            lblCostValue2.setText(String.format("%d", (int) helper.getUpgradeCost()));
            btnUpgrade2.setEnabled(true);
            btnHire2.setEnabled(true);
            if (helper.isAssigned()) {
                btnHire2.setText("Unassign");
                jPanel4.setBackground(new Color(102, 0, 0));
            } else {
                btnHire2.setText("Assign");
                jPanel4.setBackground(new Color(102, 102, 102));
                if (MainClass.assignedHelperList.size() == 3) {
                    btnHire2.setEnabled(false);
                }
            }
            if (MainClass.player.getGold() < helper.getUpgradeCost()) {
                btnUpgrade2.setEnabled(false);
            }
        } else {
            jPanel4.setBackground(new Color(51, 51, 51));
            lblCost2.setText("Hire Cost: $");
            lblCostValue2.setText(String.format("%d", (int) helper.getHireCost()));
            btnHire2.setText("Hire");
            btnUpgrade2.setEnabled(false);
            if (MainClass.player.getGold() < helper.getHireCost()) {
                btnHire2.setEnabled(false);
            } else {
                btnHire2.setEnabled(true);
            }
        }
    }

    private void updatePanel4Control(Helper helper) {
        lblIcon3.setIcon(new ImageIcon(imageFolderPath + helper.getImageUrl()));
        lblName3.setText(helper.getName());
        lblLevelValue3.setText(String.format("%d", helper.getLevel()));
        lblDamageValue3.setText(String.format("%d", (int) helper.getDamage()));

        if (helper.isHired()) {
            lblCost3.setText("Upgrade Cost: $");
            lblCostValue3.setText(String.format("%d", (int) helper.getUpgradeCost()));
            btnUpgrade3.setEnabled(true);
            btnHire3.setEnabled(true);
            if (helper.isAssigned()) {
                btnHire3.setText("Unassign");
                jPanel5.setBackground(new Color(102, 0, 0));
            } else {
                btnHire3.setText("Assign");
                jPanel5.setBackground(new Color(102, 102, 102));
                if (MainClass.assignedHelperList.size() == 3) {
                    btnHire3.setEnabled(false);
                }
            }
            if (MainClass.player.getGold() < helper.getUpgradeCost()) {
                btnUpgrade3.setEnabled(false);
            }
        } else {
            jPanel5.setBackground(new Color(51, 51, 51));
            lblCost3.setText("Hire Cost: $");
            lblCostValue3.setText(String.format("%d", (int) helper.getHireCost()));
            btnHire3.setText("Hire");
            btnUpgrade3.setEnabled(false);
            if (MainClass.player.getGold() < helper.getHireCost()) {
                btnHire3.setEnabled(false);
            } else {
                btnHire3.setEnabled(true);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHire;
    private javax.swing.JButton btnHire1;
    private javax.swing.JButton btnHire2;
    private javax.swing.JButton btnHire3;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnPrevPage;
    private javax.swing.JButton btnUpgrade;
    private javax.swing.JButton btnUpgrade1;
    private javax.swing.JButton btnUpgrade2;
    private javax.swing.JButton btnUpgrade3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelGold;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblCost1;
    private javax.swing.JLabel lblCost2;
    private javax.swing.JLabel lblCost3;
    private javax.swing.JLabel lblCostValue;
    private javax.swing.JLabel lblCostValue1;
    private javax.swing.JLabel lblCostValue2;
    private javax.swing.JLabel lblCostValue3;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JLabel lblDamage1;
    private javax.swing.JLabel lblDamage2;
    private javax.swing.JLabel lblDamage3;
    private javax.swing.JLabel lblDamageValue;
    private javax.swing.JLabel lblDamageValue1;
    private javax.swing.JLabel lblDamageValue2;
    private javax.swing.JLabel lblDamageValue3;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLevel1;
    private javax.swing.JLabel lblLevel2;
    private javax.swing.JLabel lblLevel3;
    private javax.swing.JLabel lblLevelValue;
    private javax.swing.JLabel lblLevelValue1;
    private javax.swing.JLabel lblLevelValue2;
    private javax.swing.JLabel lblLevelValue3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    // End of variables declaration//GEN-END:variables
}
