package clickerrpg.ui;

import clickerrpg.Equipment;
import clickerrpg.Consumable;
import clickerrpg.MainClass;
import clickerrpg.Player;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Chong Wai Kit
 */
public class InventoryUI extends javax.swing.JFrame {

    private static int page = 1;
    private String sortMode = "All";
    private String viewType = "Equipment";

    /**
     * Creates new form InventoryUI
     */
    public InventoryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblItemIcon = new javax.swing.JLabel();
        lblItemStats = new javax.swing.JLabel();
        btnEquip = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        lblSellPrice = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPrevPage = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();
        lblSortAll = new javax.swing.JLabel();
        lblSortWeapon = new javax.swing.JLabel();
        lblSortHelmet = new javax.swing.JLabel();
        lblSortChest = new javax.swing.JLabel();
        lblSortLeggings = new javax.swing.JLabel();
        lblSortBoots = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblItem1x1 = new javax.swing.JLabel();
        lblItem1x2 = new javax.swing.JLabel();
        lblItem1x3 = new javax.swing.JLabel();
        lblItem1x4 = new javax.swing.JLabel();
        lblItem1x5 = new javax.swing.JLabel();
        lblItem2x1 = new javax.swing.JLabel();
        lblItem2x2 = new javax.swing.JLabel();
        lblItem2x3 = new javax.swing.JLabel();
        lblItem2x4 = new javax.swing.JLabel();
        lblItem2x5 = new javax.swing.JLabel();
        lblItem3x1 = new javax.swing.JLabel();
        lblItem4x1 = new javax.swing.JLabel();
        lblItem4x2 = new javax.swing.JLabel();
        lblItem3x2 = new javax.swing.JLabel();
        lblItem3x3 = new javax.swing.JLabel();
        lblItem4x3 = new javax.swing.JLabel();
        lblItem3x4 = new javax.swing.JLabel();
        lblItem4x4 = new javax.swing.JLabel();
        lblItem3x5 = new javax.swing.JLabel();
        lblItem4x5 = new javax.swing.JLabel();
        lblSortBoots1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnShowEquipment = new javax.swing.JButton();
        btnShowConsumables = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        lblGoldIcon = new javax.swing.JLabel();
        lblGold = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHealth = new javax.swing.JLabel();
        lblAttack = new javax.swing.JLabel();
        lblDefense = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(850, 660));
        setMinimumSize(new java.awt.Dimension(850, 660));
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Inventory");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(335, 453));
        jPanel1.setMinimumSize(new java.awt.Dimension(335, 453));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Details");

        lblItemName.setBackground(new java.awt.Color(0, 0, 0));
        lblItemName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(0, 0, 0));
        lblItemName.setText("Item Name");

        lblItemIcon.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItemIcon.setForeground(new java.awt.Color(0, 0, 0));
        lblItemIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItemIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItemIcon.setMaximumSize(new java.awt.Dimension(160, 160));
        lblItemIcon.setMinimumSize(new java.awt.Dimension(160, 160));
        lblItemIcon.setPreferredSize(new java.awt.Dimension(160, 160));

        lblItemStats.setBackground(new java.awt.Color(0, 0, 0));
        lblItemStats.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblItemStats.setForeground(new java.awt.Color(0, 0, 0));
        lblItemStats.setText("Stats");
        lblItemStats.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnEquip.setBackground(new java.awt.Color(102, 102, 102));
        btnEquip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEquip.setForeground(new java.awt.Color(255, 255, 255));
        btnEquip.setText("Equip");
        btnEquip.setFocusable(false);
        btnEquip.setMaximumSize(new java.awt.Dimension(150, 35));
        btnEquip.setMinimumSize(new java.awt.Dimension(150, 35));
        btnEquip.setPreferredSize(new java.awt.Dimension(150, 35));
        btnEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipActionPerformed(evt);
            }
        });

        btnSell.setBackground(new java.awt.Color(102, 102, 102));
        btnSell.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSell.setForeground(new java.awt.Color(255, 255, 255));
        btnSell.setText("Sell");
        btnSell.setFocusable(false);
        btnSell.setMaximumSize(new java.awt.Dimension(150, 35));
        btnSell.setMinimumSize(new java.awt.Dimension(150, 35));
        btnSell.setPreferredSize(new java.awt.Dimension(150, 35));
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        lblSellPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSellPrice.setForeground(new java.awt.Color(0, 0, 0));
        lblSellPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSellPrice.setText("Sell Price");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblItemStats, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblItemIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblItemIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItemStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSellPrice))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(482, 492));
        jPanel2.setMinimumSize(new java.awt.Dimension(482, 492));

        btnPrevPage.setBackground(new java.awt.Color(102, 102, 102));
        btnPrevPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrevPage.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevPage.setText("Previous Page");
        btnPrevPage.setFocusable(false);
        btnPrevPage.setMaximumSize(new java.awt.Dimension(150, 35));
        btnPrevPage.setMinimumSize(new java.awt.Dimension(150, 35));
        btnPrevPage.setPreferredSize(new java.awt.Dimension(150, 35));
        btnPrevPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevPageActionPerformed(evt);
            }
        });

        btnNextPage.setBackground(new java.awt.Color(102, 102, 102));
        btnNextPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNextPage.setForeground(new java.awt.Color(255, 255, 255));
        btnNextPage.setFocusable(false);
        btnNextPage.setLabel("Next Page");
        btnNextPage.setMaximumSize(new java.awt.Dimension(150, 35));
        btnNextPage.setMinimumSize(new java.awt.Dimension(150, 35));
        btnNextPage.setPreferredSize(new java.awt.Dimension(150, 35));
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        lblPage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPage.setForeground(new java.awt.Color(0, 0, 0));
        lblPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPage.setText("0 / 0");
        lblPage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSortAll.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortAll.setForeground(new java.awt.Color(0, 0, 0));
        lblSortAll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/Slot_All.png"))); // NOI18N
        lblSortAll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortAll.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortAll.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortAll.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortWeapon.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortWeapon.setForeground(new java.awt.Color(0, 0, 0));
        lblSortWeapon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortWeapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/Slot_Weapon.png"))); // NOI18N
        lblSortWeapon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortWeapon.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortWeapon.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortWeapon.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortHelmet.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortHelmet.setForeground(new java.awt.Color(0, 0, 0));
        lblSortHelmet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortHelmet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/Slot_Helmet.png"))); // NOI18N
        lblSortHelmet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortHelmet.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortHelmet.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortHelmet.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortChest.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortChest.setForeground(new java.awt.Color(0, 0, 0));
        lblSortChest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortChest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/Slot_Chest.png"))); // NOI18N
        lblSortChest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortChest.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortChest.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortChest.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortLeggings.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortLeggings.setForeground(new java.awt.Color(0, 0, 0));
        lblSortLeggings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortLeggings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/Slot_Leggings.png"))); // NOI18N
        lblSortLeggings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortLeggings.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortLeggings.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortLeggings.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortBoots.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortBoots.setForeground(new java.awt.Color(0, 0, 0));
        lblSortBoots.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortBoots.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clickerrpg/img/Slot_Boots.png"))); // NOI18N
        lblSortBoots.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortBoots.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortBoots.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortBoots.setPreferredSize(new java.awt.Dimension(40, 40));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        lblItem1x1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x1.setMaximumSize(new java.awt.Dimension(80, 80));
        lblItem1x1.setMinimumSize(new java.awt.Dimension(80, 80));
        lblItem1x1.setNextFocusableComponent(lblItem1x2);
        lblItem1x1.setPreferredSize(new java.awt.Dimension(80, 80));
        lblItem1x1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemClicked(evt);
            }
        });

        lblItem1x2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x2.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem1x2.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem1x2.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem1x3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x3.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem1x3.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem1x3.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem1x4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x4.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem1x4.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem1x4.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem1x5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x5.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem1x5.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem1x5.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x1.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x1.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x1.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x2.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x2.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x2.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x3.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x3.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x3.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x4.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x4.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x4.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x5.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x5.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x5.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x1.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x1.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x1.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x1.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x1.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x1.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x2.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x2.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x2.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x2.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x2.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x2.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x3.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x3.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x3.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x3.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x3.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x3.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x4.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x4.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x4.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x4.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x4.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x4.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x5.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x5.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x5.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x5.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x5.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x5.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblItem2x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblItem2x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblItem2x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblItem2x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblItem1x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblItem1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblItem1x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblItem1x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItem2x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItem3x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem4x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblItem3x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblItem3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblItem3x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblItem4x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblItem4x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblItem4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItem4x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem3x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItem1x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItem2x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem2x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem2x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem2x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem2x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblItem3x2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblItem3x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblItem3x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem3x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItem4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItem4x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItem4x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItem4x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItem4x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        lblSortBoots1.setBackground(new java.awt.Color(153, 153, 153));
        lblSortBoots1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortBoots1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortBoots1.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortBoots1.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortBoots1.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPrevPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPage, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSortAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSortWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSortHelmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSortChest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSortLeggings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSortBoots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSortBoots1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSortAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortHelmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortChest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortLeggings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortBoots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortBoots1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPage))
                .addContainerGap())
        );

        btnShowEquipment.setBackground(new java.awt.Color(102, 102, 102));
        btnShowEquipment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnShowEquipment.setForeground(new java.awt.Color(255, 255, 255));
        btnShowEquipment.setText("Equipment");
        btnShowEquipment.setFocusable(false);
        btnShowEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowEquipmentActionPerformed(evt);
            }
        });

        btnShowConsumables.setBackground(new java.awt.Color(102, 102, 102));
        btnShowConsumables.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnShowConsumables.setForeground(new java.awt.Color(255, 255, 255));
        btnShowConsumables.setText("Consumables");
        btnShowConsumables.setFocusable(false);
        btnShowConsumables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowConsumablesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShowEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowConsumables)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowConsumables))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backButton.setBackground(new java.awt.Color(102, 102, 102));
        backButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setFocusable(false);
        backButton.setMaximumSize(new java.awt.Dimension(150, 35));
        backButton.setMinimumSize(new java.awt.Dimension(150, 35));
        backButton.setPreferredSize(new java.awt.Dimension(150, 35));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblGoldIcon.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblGoldIcon.setForeground(new java.awt.Color(255, 215, 0));
        lblGoldIcon.setText("$");

        lblGold.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblGold.setForeground(new java.awt.Color(255, 215, 0));
        lblGold.setText("999 999 999");
        lblGold.setName(""); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Health :");
        jLabel2.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Attack :");
        jLabel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Defense :");
        jLabel4.setToolTipText("");

        lblHealth.setBackground(new java.awt.Color(0, 0, 0));
        lblHealth.setForeground(new java.awt.Color(0, 0, 0));
        lblHealth.setText("100 / 100");

        lblAttack.setBackground(new java.awt.Color(0, 0, 0));
        lblAttack.setForeground(new java.awt.Color(0, 0, 0));
        lblAttack.setText("100000");

        lblDefense.setBackground(new java.awt.Color(0, 0, 0));
        lblDefense.setForeground(new java.awt.Color(0, 0, 0));
        lblDefense.setText("100000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHealth))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAttack))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDefense)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblHealth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblAttack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDefense))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGoldIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGold)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblGoldIcon)
                                .addComponent(lblGold)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainClass.gameUI.updateGameUI();
        MainClass.gameUI.setEnabled(true);
        MainClass.startAutoAttackTimers();
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void itemClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemClicked
        JLabel jLabel = (JLabel) evt.getSource();
        if (jLabel.getClientProperty("item") == null) return;

        switch (viewType) {
            case "Equipment":
                showDetails((Equipment) jLabel.getClientProperty("item"));
                break;
            case "Consumables":
                showDetails((Consumable) jLabel.getClientProperty("item"));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_itemClicked

    private void btnEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipActionPerformed
        JButton jButton = (JButton) evt.getSource();
        switch (viewType) {
            case "Equipment":
                Equipment equipment = (Equipment) jButton.getClientProperty("item");
                if (equipment.isEquipped()) {
                    MainClass.player.unequipEquipment(equipment);
                } else {
                    Equipment unequippedItem = MainClass.player.equipEquipment(equipment);
                    if (unequippedItem != null) {
                        MainClass.equipmentInventory.sortItem(unequippedItem);
                    }
                }

                MainClass.equipmentInventory.sortItem(equipment);

                loadEquipment();
                showDetails(equipment);
                break;
            case "Consumables":
                Consumable consumable = (Consumable) jButton.getClientProperty("item");
                
                MainClass.player.consume(consumable);
                
                MainClass.consumableInventory.remove(consumable);
                
                loadConsumables();
                showDetails(consumable);
                break;

        }


    }//GEN-LAST:event_btnEquipActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        JButton jButton = (JButton) evt.getSource();
        switch (viewType) {
            case "Equipment":
                Equipment equipment = (Equipment) jButton.getClientProperty("item");
                equipment.unequip();
                MainClass.equipmentInventory.remove(equipment);
                MainClass.player.addGold(equipment.getPrice());
                clearData();
                loadEquipment();
                break;
            case "Consumables":
                Consumable consumable = (Consumable) jButton.getClientProperty("item");
                MainClass.consumableInventory.remove(consumable);
                MainClass.player.addGold(consumable.getPrice());
                clearData();
                loadConsumables();
                break;

        }


    }//GEN-LAST:event_btnSellActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        page++;
        loadEquipment();
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void btnPrevPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevPageActionPerformed
        page--;
        loadEquipment();
    }//GEN-LAST:event_btnPrevPageActionPerformed

    private void btnShowEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowEquipmentActionPerformed
        viewType = "Equipment";
        loadEquipment();
    }//GEN-LAST:event_btnShowEquipmentActionPerformed

    private void btnShowConsumablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowConsumablesActionPerformed
        viewType = "Consumables";
        loadConsumables();
    }//GEN-LAST:event_btnShowConsumablesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryUI().setVisible(true);
            }
        });
    }

    public void startUp() {
        page = 1;
        sortMode = "All";
        setLocationRelativeTo(null);
        setMouseListeners();
        loadEquipment();
        setVisible(true);
    }

    private void setMouseListeners() {
        JLabel[] labels
                = {lblItem1x1, lblItem1x2, lblItem1x3, lblItem1x4, lblItem1x5,
                    lblItem2x1, lblItem2x2, lblItem2x3, lblItem2x4, lblItem2x5,
                    lblItem3x1, lblItem3x2, lblItem3x3, lblItem3x4, lblItem3x5,
                    lblItem4x1, lblItem4x2, lblItem4x3, lblItem4x4, lblItem4x5};

        for (JLabel label : labels) {
            label.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    itemClicked(evt);
                }
            });
        }

        lblSortAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortMode = "All";
                page = 1;
                loadEquipment();
            }
        });

        lblSortWeapon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortMode = "Weapon";
                page = 1;
                loadEquipment();
            }
        });

        lblSortHelmet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortMode = "Helmet";
                page = 1;
                loadEquipment();
            }
        });
        lblSortChest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortMode = "Chest";
                page = 1;
                loadEquipment();
            }
        });

        lblSortLeggings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortMode = "Leggings";
                page = 1;
                loadEquipment();
            }
        });

        lblSortBoots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortMode = "Boots";
                page = 1;
                loadEquipment();
            }
        });
    }

    private void showDetails(Equipment equipment) {
        lblItemIcon.setIcon(new ImageIcon(equipment.getImageIcon().getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        lblItemName.setText(equipment.getEqName());

        btnEquip.setVisible(true);
        btnSell.setVisible(true);

        String itemStats = "";

        itemStats += "<html><p>" + equipment.getEqSlot();
        if (equipment.isEquipped()) {
            itemStats += " ( EQUIPPED )";
        }
        if (equipment.getAttack() != 0) {
            itemStats += "<br>Attack : " + equipment.getAttack();
        }
        if (equipment.getDefense() != 0) {
            itemStats += "<br>Defense : " + equipment.getDefense();
        }
        if (equipment.getHealth() != 0) {
            itemStats += "<br>Health : " + equipment.getHealth();
        }

        itemStats += "</p></html>";

        lblItemStats.setText(itemStats);

        if (equipment.isEquipped()) {
            btnEquip.setText("Unequip");
        } else {
            btnEquip.setText("Equip");
        }

        btnEquip.putClientProperty("item", equipment);
        btnSell.putClientProperty("item", equipment);

        lblSellPrice.setText(String.valueOf(equipment.getPrice()));
    }

    private void showDetails(Consumable consumable) {
        lblItemIcon.setIcon(new ImageIcon(consumable.getImageIcon().getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        lblItemName.setText(consumable.getConsName());

        String itemStats = "";
        itemStats += "<html><p>";
        if (consumable.getHealthIncreased() > 0) {
            itemStats += "Heals for " + String.valueOf(consumable.getHealthIncreased()) + " health.";
        }

        itemStats += "</p></html>";

        lblItemStats.setText(itemStats);

        btnEquip.putClientProperty("item", consumable);
        btnSell.putClientProperty("item", consumable);

        lblSellPrice.setText(String.valueOf(consumable.getPrice()));

        btnEquip.setText("Use");
        btnEquip.setVisible(true);
        btnSell.setVisible(true);

    }

    private void clearData() {
        lblGold.setText(String.format("%d", (int) MainClass.player.getGold()));

        JLabel[] labels
                = {lblItem1x1, lblItem1x2, lblItem1x3, lblItem1x4, lblItem1x5,
                    lblItem2x1, lblItem2x2, lblItem2x3, lblItem2x4, lblItem2x5,
                    lblItem3x1, lblItem3x2, lblItem3x3, lblItem3x4, lblItem3x5,
                    lblItem4x1, lblItem4x2, lblItem4x3, lblItem4x4, lblItem4x5};

        for (int i = 0; i < 20; i++) {
            JLabel label = labels[i];
            label.setIcon(null);
            label.setText(null);
            label.putClientProperty("item", null);
        }

        lblItemIcon.setIcon(null);
        lblItemName.setText(null);
        lblItemStats.setText(null);
        btnEquip.setVisible(false);
        btnSell.setVisible(false);
        lblSellPrice.setText(null);

        btnEquip.putClientProperty("equipment", null);
        btnSell.putClientProperty("equipment", null);
        
        Player player = MainClass.player;
        lblHealth.setText(String.valueOf((int)player.getCurHealth()) + " / " + String.valueOf((int)player.getMaxHealth()));
        lblAttack.setText(String.valueOf((int)player.getAttack()));
        lblDefense.setText(String.valueOf((int)player.getDefense()));

    }

    private void loadEquipment() {
        clearData();

        changeEqSortButtonVisibility(true);

        lblPage.setText("Page " + String.valueOf(page));

        JLabel[] labels
                = {lblItem1x1, lblItem1x2, lblItem1x3, lblItem1x4, lblItem1x5,
                    lblItem2x1, lblItem2x2, lblItem2x3, lblItem2x4, lblItem2x5,
                    lblItem3x1, lblItem3x2, lblItem3x3, lblItem3x4, lblItem3x5,
                    lblItem4x1, lblItem4x2, lblItem4x3, lblItem4x4, lblItem4x5};

        // i = iterator for Equipment, j = iterator for jlabel
        for (int i = (page * 20) - 20, j = 0;
                i < MainClass.equipmentInventory.getLength() && j < 20;
                i++, j++) {
            JLabel label = labels[j];
            Equipment equipment = MainClass.equipmentInventory.getEntry(i);

            // if eqSlot is not All & eqSlot not equal, skip to next i
            if (!sortMode.equals("All") && !sortMode.equals(equipment.getEqSlot())) {
                j--;
                continue;
            }

            label.putClientProperty("item", equipment);
            label.setIcon(equipment.getImageIcon());

            int eqItems = 0;
            if (MainClass.player.getWeapon() != null) { eqItems++ ;}
            if (MainClass.player.getHelmet()!= null) { eqItems++ ;}
            if (MainClass.player.getChest() != null) { eqItems++ ;}
            if (MainClass.player.getLeggings()!= null) { eqItems++ ;}
            if (MainClass.player.getBoots()!= null) { eqItems++ ;}
           
            if ( j < eqItems) {
                label.setHorizontalTextPosition(JLabel.LEFT);
                label.setVerticalTextPosition(JLabel.TOP);

                label.setIcon(equipment.getImageIcon());
                label.setIconTextGap(-75);

                label.setFont(new Font("Arial", Font.BOLD, 25));
                label.setText("E");

            } else {
                label.setText("");
            }

            //disable next page if j is not full
            if (j == 19) {
                btnNextPage.setEnabled(true);
            } else {
                btnNextPage.setEnabled(false);
            }

        }

        if (page == 1) {
            btnPrevPage.setEnabled(false);
        } else {
            btnPrevPage.setEnabled(true);
        }

    }

    private void loadConsumables() {
        clearData();
        changeEqSortButtonVisibility(false);

        lblPage.setText("Page " + String.valueOf(page));

        JLabel[] labels
                = {lblItem1x1, lblItem1x2, lblItem1x3, lblItem1x4, lblItem1x5,
                    lblItem2x1, lblItem2x2, lblItem2x3, lblItem2x4, lblItem2x5,
                    lblItem3x1, lblItem3x2, lblItem3x3, lblItem3x4, lblItem3x5,
                    lblItem4x1, lblItem4x2, lblItem4x3, lblItem4x4, lblItem4x5};

        // i = iterator for Consumable, j = iterator for jlabel
        for (int i = (page * 20) - 20, j = 0;
                i < MainClass.consumableInventory.getLength() && j < 20;
                i++, j++) {
            JLabel label = labels[j];
            Consumable consumable = MainClass.consumableInventory.getEntry(i);

            label.putClientProperty("item", consumable);
            label.setIcon(consumable.getImageIcon());

            //disable next page if j is not full
            if (j == 19) {
                btnNextPage.setEnabled(true);
            } else {
                btnNextPage.setEnabled(false);
            }

        }

        if (page == 1) {
            btnPrevPage.setEnabled(false);
        } else {
            btnPrevPage.setEnabled(true);
        }

    }

    private void changeEqSortButtonVisibility(Boolean visibility) {
        lblSortAll.setVisible(visibility);
        lblSortHelmet.setVisible(visibility);
        lblSortBoots.setVisible(visibility);
        lblSortWeapon.setVisible(visibility);
        lblSortChest.setVisible(visibility);
        lblSortLeggings.setVisible(visibility);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnEquip;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnPrevPage;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnShowConsumables;
    private javax.swing.JButton btnShowEquipment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblAttack;
    private javax.swing.JLabel lblDefense;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblGoldIcon;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblItem1x1;
    private javax.swing.JLabel lblItem1x2;
    private javax.swing.JLabel lblItem1x3;
    private javax.swing.JLabel lblItem1x4;
    private javax.swing.JLabel lblItem1x5;
    private javax.swing.JLabel lblItem2x1;
    private javax.swing.JLabel lblItem2x2;
    private javax.swing.JLabel lblItem2x3;
    private javax.swing.JLabel lblItem2x4;
    private javax.swing.JLabel lblItem2x5;
    private javax.swing.JLabel lblItem3x1;
    private javax.swing.JLabel lblItem3x2;
    private javax.swing.JLabel lblItem3x3;
    private javax.swing.JLabel lblItem3x4;
    private javax.swing.JLabel lblItem3x5;
    private javax.swing.JLabel lblItem4x1;
    private javax.swing.JLabel lblItem4x2;
    private javax.swing.JLabel lblItem4x3;
    private javax.swing.JLabel lblItem4x4;
    private javax.swing.JLabel lblItem4x5;
    private javax.swing.JLabel lblItemIcon;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemStats;
    private javax.swing.JLabel lblPage;
    private javax.swing.JLabel lblSellPrice;
    private javax.swing.JLabel lblSortAll;
    private javax.swing.JLabel lblSortBoots;
    private javax.swing.JLabel lblSortBoots1;
    private javax.swing.JLabel lblSortChest;
    private javax.swing.JLabel lblSortHelmet;
    private javax.swing.JLabel lblSortLeggings;
    private javax.swing.JLabel lblSortWeapon;
    // End of variables declaration//GEN-END:variables
}
