package clickerrpg.ui;

import clickerrpg.MainClass;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Chong Wai Kit
 */
public class InventoryUI extends javax.swing.JFrame {

    private static int page = 1;

    /**
     * Creates new form InventoryUI
     */
    public InventoryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPrevPage = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();
        lblItem1x1 = new javax.swing.JLabel();
        lblItem1x2 = new javax.swing.JLabel();
        lblItem1x3 = new javax.swing.JLabel();
        lblItem1x4 = new javax.swing.JLabel();
        lblItem1x5 = new javax.swing.JLabel();
        lblItem2x1 = new javax.swing.JLabel();
        lblItem2x2 = new javax.swing.JLabel();
        lblItem2x3 = new javax.swing.JLabel();
        lblItem2x4 = new javax.swing.JLabel();
        lblItem2x5 = new javax.swing.JLabel();
        lblItem3x1 = new javax.swing.JLabel();
        lblItem3x2 = new javax.swing.JLabel();
        lblItem3x3 = new javax.swing.JLabel();
        lblItem3x4 = new javax.swing.JLabel();
        lblItem3x5 = new javax.swing.JLabel();
        lblItem4x1 = new javax.swing.JLabel();
        lblItem4x2 = new javax.swing.JLabel();
        lblItem4x3 = new javax.swing.JLabel();
        lblItem4x4 = new javax.swing.JLabel();
        lblItem4x5 = new javax.swing.JLabel();
        lblSortAll = new javax.swing.JLabel();
        lblSortWeapon = new javax.swing.JLabel();
        lblSortHelmet = new javax.swing.JLabel();
        lblSortChest = new javax.swing.JLabel();
        lblSortLeggings = new javax.swing.JLabel();
        lblSortBoots = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 660));
        setMinimumSize(new java.awt.Dimension(850, 660));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 660));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Inventory");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("9999 / 9999");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPrevPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrevPage.setText("Previous Page");
        btnPrevPage.setMaximumSize(new java.awt.Dimension(150, 35));
        btnPrevPage.setMinimumSize(new java.awt.Dimension(150, 35));
        btnPrevPage.setPreferredSize(new java.awt.Dimension(150, 35));

        btnNextPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNextPage.setLabel("Next Page");
        btnNextPage.setMaximumSize(new java.awt.Dimension(150, 35));
        btnNextPage.setMinimumSize(new java.awt.Dimension(150, 35));
        btnNextPage.setPreferredSize(new java.awt.Dimension(150, 35));

        lblPage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPage.setText("0 / 0");
        lblPage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblItem1x1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x1.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem1x1.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem1x1.setNextFocusableComponent(lblItem1x2);
        lblItem1x1.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem1x2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x2.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem1x2.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem1x2.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem1x3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x3.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem1x3.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem1x3.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem1x4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x4.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem1x4.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem1x4.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem1x5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem1x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1x5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1x5.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem1x5.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem1x5.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x1.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x1.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x1.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x2.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x2.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x2.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x3.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x3.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x3.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x4.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x4.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x4.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem2x5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem2x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem2x5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem2x5.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem2x5.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem2x5.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x1.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x1.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x1.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x2.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x2.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x2.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x3.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x3.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x3.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x4.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x4.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x4.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem3x5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem3x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem3x5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem3x5.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem3x5.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem3x5.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x1.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x1.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x1.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x2.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x2.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x2.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x3.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x3.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x3.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x4.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x4.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x4.setPreferredSize(new java.awt.Dimension(80, 80));

        lblItem4x5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblItem4x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem4x5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem4x5.setMaximumSize(new java.awt.Dimension(70, 70));
        lblItem4x5.setMinimumSize(new java.awt.Dimension(70, 70));
        lblItem4x5.setPreferredSize(new java.awt.Dimension(80, 80));

        lblSortAll.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortAll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortAll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortAll.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortAll.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortAll.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortWeapon.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortWeapon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortWeapon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortWeapon.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortWeapon.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortWeapon.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortHelmet.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortHelmet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortHelmet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortHelmet.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortHelmet.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortHelmet.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortChest.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortChest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortChest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortChest.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortChest.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortChest.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortLeggings.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortLeggings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortLeggings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortLeggings.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortLeggings.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortLeggings.setPreferredSize(new java.awt.Dimension(40, 40));

        lblSortBoots.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblSortBoots.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortBoots.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSortBoots.setMaximumSize(new java.awt.Dimension(70, 70));
        lblSortBoots.setMinimumSize(new java.awt.Dimension(70, 70));
        lblSortBoots.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPrevPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPage, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSortAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSortWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblItem1x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItem2x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItem3x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItem4x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblItem1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblItem1x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblItem1x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblItem1x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSortHelmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSortChest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSortLeggings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSortBoots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblItem2x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItem3x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItem4x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblItem2x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItem3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItem4x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblItem2x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItem3x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItem4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblItem2x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItem3x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItem4x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSortAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortHelmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortChest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortLeggings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSortBoots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItem1x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem1x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblItem2x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem3x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem4x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblItem2x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem3x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem4x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblItem2x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem4x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblItem2x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem3x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblItem2x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem3x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblItem4x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPage))
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Equipment");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Consumables");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backButton.setText("Back");
        backButton.setMaximumSize(new java.awt.Dimension(150, 35));
        backButton.setMinimumSize(new java.awt.Dimension(150, 35));
        backButton.setPreferredSize(new java.awt.Dimension(150, 35));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 185, Short.MAX_VALUE)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryUI().setVisible(true);
            }
        });
    }

    public void startUp() {
        setAlwaysOnTop(true);
        setLocationRelativeTo(null);
        loadData();
        setVisible(true);
    }

    private void loadData() {
        JLabel[] labels
                = {lblItem1x1, lblItem1x2, lblItem1x3, lblItem1x4, lblItem1x5,
                    lblItem2x1, lblItem2x2, lblItem2x3, lblItem2x4, lblItem2x5,
                    lblItem3x1, lblItem3x2, lblItem3x3, lblItem3x4, lblItem3x5,
                    lblItem4x1, lblItem4x2, lblItem4x3, lblItem4x4, lblItem4x5};

        // i = iterator for Equipment, j = iterator for jlabel
        for (int i = (page * 20) - 20, j = 0;
                i < MainClass.equipmentInventory.getLength() && i < (page * 20) - 1;
                i++, j++) {
            labels[j].setIcon(MainClass.equipmentInventory.getEntry(i).getImageIcon());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnPrevPage;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblItem1x1;
    private javax.swing.JLabel lblItem1x2;
    private javax.swing.JLabel lblItem1x3;
    private javax.swing.JLabel lblItem1x4;
    private javax.swing.JLabel lblItem1x5;
    private javax.swing.JLabel lblItem2x1;
    private javax.swing.JLabel lblItem2x2;
    private javax.swing.JLabel lblItem2x3;
    private javax.swing.JLabel lblItem2x4;
    private javax.swing.JLabel lblItem2x5;
    private javax.swing.JLabel lblItem3x1;
    private javax.swing.JLabel lblItem3x2;
    private javax.swing.JLabel lblItem3x3;
    private javax.swing.JLabel lblItem3x4;
    private javax.swing.JLabel lblItem3x5;
    private javax.swing.JLabel lblItem4x1;
    private javax.swing.JLabel lblItem4x2;
    private javax.swing.JLabel lblItem4x3;
    private javax.swing.JLabel lblItem4x4;
    private javax.swing.JLabel lblItem4x5;
    private javax.swing.JLabel lblPage;
    private javax.swing.JLabel lblSortAll;
    private javax.swing.JLabel lblSortBoots;
    private javax.swing.JLabel lblSortChest;
    private javax.swing.JLabel lblSortHelmet;
    private javax.swing.JLabel lblSortLeggings;
    private javax.swing.JLabel lblSortWeapon;
    // End of variables declaration//GEN-END:variables
}
